{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gotway.fullname" . }}
  labels:
    {{ include "gotway.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - gotway.io
    resources:
      - ingresshttps
    verbs:
      - get
      - list
      - watch
  {{ if .Values.ha.enabled }}
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - watch
      - create
      - update
  {{ end }}
{{ end }}