nameOverride: ""
fullnameOverride: ""

env: production

logLevel: info

image:
  repository: gotwaygateway/gotway
  pullPolicy: IfNotPresent
  tag: "v0.0.11"

service:
  type: NodePort
  interalPort: 443
  externalPort: 4433

secretRef:
  name: gotway

tlsEnabled: true

gatewayTimeout: 5

healthCheck:
  enabled: true
  numWorkers: 10
  bufferSize: 10
  intervalSeconds: 10
  timeoutSeconds: 5

cache:
  enabled: true
  numWorkers: 10
  bufferSize: 10

monitoring:
  enabled: true
  path: /metrics
  port: 2112
  namespace: monitoring
  interval: 10s
  labels:
    release: monitoring

pprof:
  enabled: false
  port: 6060

livenessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 3
  periodSeconds: 15

readinessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 3
  periodSeconds: 15

resources:
  requests:
    cpu: 100m
    memory: "128Mi"
  limits:
    cpu: 300m
    memory: "512Mi"

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

nodeSelector: {}

examples:
  enabled: true

  catalog:
    image:
      repository: gotwaygateway/catalog
      pullPolicy: IfNotPresent
      tag: "v0.0.3"

    service:
      type: ClusterIP
      port: 80

    livenessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 3
      periodSeconds: 15

    readinessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 3
      periodSeconds: 15

    resources: {}

    nodeSelector: {}

  stock:
    image:
      repository: gotwaygateway/stock
      pullPolicy: IfNotPresent
      tag: "v0.0.3"

    service:
      type: ClusterIP
      port: 80

    redis:
      address: gotway-redis:6379
      db: 1
      prefix: "stock::"
      ttlDefault: 300
      ttlMax: 86400

    livenessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 3
      periodSeconds: 15

    readinessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 3
      periodSeconds: 15

    resources: {}

    nodeSelector: {}

  traffic:
    enabled: false

    image:
      repository: gotwaygateway/traffic
      pullPolicy: IfNotPresent
      tag: "v0.0.1"

    gotwayHost: "gotway.duckdns.org:4433"
    catalogHost: "catalog.gotway.duckdns.org:4433"
    stockHost: "stock.gotway.duckdns.org:4433"

    clientTimeout: 10

    numWorkers: 5

    numClients: 2

    requestInterval: 10

    resources: {}

    nodeSelector: {}

# dependencies

redis:
  prometheus-redis-exporter:
    redisAddress: redis://gotway-redis:6379
    serviceMonitor:
      labels:
        release: monitoring
