apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gotway.fullname" . }}
  labels:
    {{ include "gotway.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.interalPort | quote }}
  ENV: {{ .Values.env }}
  LOG_LEVEL: {{ .Values.logLevel }}
  HEALTH_CHECK_NUM_WORKERS: {{ .Values.healthCheck.numWorkers | quote }}
  HEALTH_CHECK_BUFFER_SIZE: {{ .Values.healthCheck.bufferSize | quote }}
  HEALTH_CHECK_INTERVAL_SECONDS: {{ .Values.healthCheck.intervalSeconds | quote }}
  HEALTH_CHECK_TIMEOUT_SECONDS: {{ .Values.healthCheck.timeoutSeconds | quote }}
  TLS: {{ .Values.tlsEnabled | quote }}
  {{ if .Values.tlsEnabled }}
  TLS_CERT: "/etc/ssl/tls.crt"
  TLS_KEY: "/etc/ssl/tls.key"
  {{ end }}
  METRICS: {{ .Values.monitoring.enabled | quote }}
  METRICS_PATH: {{ .Values.monitoring.path }}
  METRICS_PORT: {{ .Values.monitoring.port | quote }}