{{ $fullname := include "gotway.fullname" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}
  labels:
    {{ include "gotway.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  ENV: {{ .Values.env }}
  LOG_LEVEL: {{ .Values.logLevel }}
  {{ with .Values.redisUrl }}
  REDIS_URL: {{ . | quote }}
  {{ end }}
  GATEWAY_TIMEOUT_SECONDS: {{ .Values.gatewayTimeout | quote }}
  HA: {{ .Values.ha.enabled | quote }}
  {{ if .Values.ha.enabled }}
  HA_LEASE_LOCK_NAME: {{ $fullname | quote }}
  HA_LEASE_LOCK_NAMESPACE: {{ .Release.Namespace | quote }}
  HA_LEASE_DURATION_SECONDS: {{ .Values.ha.leaderElection.leaseDurationSeconds | quote }}
  HA_RENEW_DEADLINE_SECONDS: {{ .Values.ha.leaderElection.renewDeadlineSeconds | quote }}
  HA_RETRY_PERIOD_SECONDS: {{ .Values.ha.leaderElection.retryPeriodSeconds | quote }}
  {{ end }}
  HEALTH: {{ .Values.healthCheck.enabled | quote }}
  {{ if .Values.healthCheck.enabled }}
  HEALTH_CHECK_NUM_WORKERS: {{ .Values.healthCheck.numWorkers | quote }}
  HEALTH_CHECK_BUFFER_SIZE: {{ .Values.healthCheck.bufferSize | quote }}
  HEALTH_CHECK_INTERVAL_SECONDS: {{ .Values.healthCheck.intervalSeconds | quote }}
  HEALTH_CHECK_TIMEOUT_SECONDS: {{ .Values.healthCheck.timeoutSeconds | quote }}
  {{ end }}
  CACHE: {{ .Values.cache.enabled | quote }}
  {{ if .Values.cache.enabled }}
  CACHE_NUM_WORKERS: {{ .Values.cache.numWorkers | quote }}
  CACHE_BUFFER_SIZE: {{ .Values.cache.bufferSize | quote }}
  {{ end }}
  TLS: {{ .Values.tlsEnabled | quote }}
  {{ if .Values.tlsEnabled }}
  TLS_CERT: "/etc/ssl/tls.crt"
  TLS_KEY: "/etc/ssl/tls.key"
  {{ end }}
  METRICS: {{ .Values.monitoring.enabled | quote }}
  {{ if .Values.monitoring.enabled }}
  METRICS_PATH: {{ .Values.monitoring.path }}
  METRICS_PORT: {{ .Values.monitoring.port | quote }}
  {{ end }}
  PPROF: {{ .Values.pprof.enabled | quote }}
  {{ if .Values.pprof.enabled }}
  PPROF_PORT: {{ .Values.pprof.port | quote }}
  {{ end}}