{{ $fullName := include "gotway.fullname" . }}
{{ $selectorLabels := include "gotway.selectorLabels" . }}
{{ with .Values.metrics }}
{{ if .enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}
  namespace: {{ .serviceMonitor.namespace }}
  {{ with .serviceMonitor.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  selector:
      matchLabels:
        {{ $selectorLabels | nindent 8 }}
  namespaceSelector:
    any: true
  endpoints:
    - targetPort: {{ .port }}
      path: {{ .path }}
      interval: {{ .serviceMonitor.interval }}
      scrapeTimeout: {{ .serviceMonitor.timeout }}
{{ end }}
{{ end }}